Repository next-step/js-todo-list-step3, pull requests merged in 2021-03, with the labels that each got.

#24 [Suppplier] TODOLIST For Team
  index.html
  js/API.js
  js/App.js
  js/Team.js
  js/teamlist/AddTeam.js
  js/teamlist/DeleteTeam.js
  js/teamlist/ShowTeamList.js
  js/teamlist/Team.js
  js/teamlist/Team_DOM.js
  js/todolist/AddItem.js
  js/todolist/AddMember.js
  js/todolist/CheckItem.js
  js/todolist/ControlTodoButton.js
  js/todolist/DeleteAllItems.js
  js/todolist/DeleteItem.js
  js/todolist/PrioritizeItem.js
  js/todolist/ShowTodoList.js
  js/todolist/TodoList.js
  js/todolist/TodoList_DOM.js
  js/todolist/UpdateItem.js
  js/validator.js
  kanban.html
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#25 [6기 WOO] TodoList for Team
  .eslintrc.js
  .gitignore
  README.md
  index.html
  js/App.js
  js/Team.js
  kanban.html
  package-lock.json
  package.json
  src/App.js
  src/api/index.js
  src/api/module/teamApi.js
  src/api/module/todoApi.js
  src/api/utils/method.js
  src/api/utils/request.js
  src/components/kanban/TodoContainer.js
  src/components/kanban/TodoCount.js
  src/components/kanban/TodoFilter.js
  src/components/kanban/TodoFilterItem.js
  src/components/kanban/TodoInput.js
  src/components/kanban/TodoList.js
  src/components/kanban/TodoListItem.js
  src/components/kanban/index.js
  src/components/main/TeamCard.js
  src/components/main/index.js
  src/index.css
  src/index.js
  src/router/index.js
  src/store/index.js
  src/store/module/teamState.js
  src/store/module/todoState.js
  src/utils/constants.js
  src/utils/createElement.js
  webpack.config.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#26 [hongjehong] TodoList for Team
  index.html
  js/API.js
  js/App.js
  js/Team.js
  js/Team/AddTodoItem.js
  js/Team/AddUser.js
  js/Team/DeleteTodoItem.js
  js/Team/DeleteTodoItemAll.js
  js/Team/LoadTeam.js
  js/Team/LoadTodoList.js
  js/Team/ModifyContents.js
  js/Team/SetPriority.js
  js/Team/Team.js
  js/Team/TodoList.js
  js/Team/ToggleTodoItem.js
  js/TeamList/AddTeam.js
  js/TeamList/LoadTeamList.js
  js/TeamList/TeamList.js
  js/template.js
  kanban.html
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#27 [Kwonkyu] TodoList For Team
  index.html
  js/App.js
  js/Team.js
  js/client/app/drawMember.js
  js/client/app/drawTodo.js
  js/client/app/initMember.js
  js/client/app/todoList/animationToggler.js
  js/client/app/todoList/filters/applyPriorityFilter.js
  js/client/app/todoList/filters/filterRules.js
  js/client/app/todoList/initCountContainer.js
  js/client/app/todoList/initInputContainer.js
  js/client/app/todoList/initTodoListMain.js
  js/client/app/todoList/todoListEventHandlers/onChangeTodoList.js
  js/client/app/todoList/todoListEventHandlers/onClickTodoList.js
  js/client/app/todoList/todoListEventHandlers/onDoubleClickTodoList.js
  js/client/app/todoList/todoListEventHandlers/onKeyUpTodoList.js
  js/client/app/todoList/updateCountText.js
  js/client/team/drawTeam.js
  js/client/team/initTeam.js
  js/serverAPI/constant.js
  js/serverAPI/fetch.js
  js/serverAPI/requestOption.js
  js/serverAPI/team/addTeam.js
  js/serverAPI/team/deleteTeam.js
  js/serverAPI/team/loadTeam.js
  js/serverAPI/tryRequest.js
  js/serverAPI/user/addMember.js
  js/serverAPI/user/addTodo.js
  js/serverAPI/user/deleteAllTodo.js
  js/serverAPI/user/deleteTodo.js
  js/serverAPI/user/loadTodoList.js
  js/serverAPI/user/toggleTodo.js
  js/serverAPI/user/updatePriority.js
  js/serverAPI/user/updateTodo.js
  kanban.html
Labels: TeamB, 🏆 미션완료, 🚨 리뷰 요청

#29 [6기 khw970421] TodoList For Team
  index.html
  js/App.js
  js/App/AddMemberEvent.js
  js/App/membersLiItemEvent.js
  js/App/todoAppCountContainer.js
  js/Team.js
  js/content/requestOption.js
  js/content/shape.js
  js/index/AddTeamEvent.js
  js/server/AppServer.js
  js/server/indexServer.js
  kanban.html
Labels: TeamB, 🚀 필수미션, 🚨 리뷰 요청

#30 [ 6기 DD ] Todolist For Team
  README.md
  css/style.css
  index.html
  js/App.js
  js/Member.js
  js/Team.js
  js/api/api.js
  js/components/MemberAppender.js
  js/components/TeamCard.js
  js/components/TodoApp.js
  js/components/TodoAppender.js
  js/components/TodoFilter.js
  js/components/TodoList.js
  js/core/component.js
  kanban.html
Labels: TeamC, 🏆 미션완료, 🚀 필수미션, 🚨 리뷰 요청

#31 [6기 Jiseon Kim] TodoList for Team
  .eslintrc.json
  .gitignore
  .prettierrc
  css/style.css
  index.html
  js/App.js
  js/Team.js
  kanban.html
  package-lock.json
  src/Team/Team.js
  src/Team/createTeam.js
  src/Team/loadTeam.js
  src/Team/removeTeam.js
  src/Todo/feature/addMember.js
  src/Todo/feature/completeTodo.js
  src/Todo/feature/editTodo.js
  src/Todo/feature/removeTodo.js
  src/Todo/feature/setPriority.js
  src/Todo/feature/todoCount.js
  src/Todo/feature/todoInput.js
  src/Todo/loadTodo.js
  src/Todo/todo.js
  src/Todo/todoRender.js
  src/etc/api.js
  src/etc/dom.js
  src/etc/template.js
  src/etc/validator.js
Labels: TeamC, 🚀 필수미션, 🚨 리뷰 요청

#32 [6기 yeewon] TodoList For Team
  .vscode/settings.json
  css/style.css
  index.html
  js/App.js
  js/Team.js
  kanban.html
  src/api/api.js
  src/components/memberList/addMember.js
  src/components/memberList/loadMembers.js
  src/components/memberList/memberList.js
  src/components/memberList/memberTemplates.js
  src/components/teamList/addTeam.js
  src/components/teamList/controlTitle.js
  src/components/teamList/loadTeams.js
  src/components/teamList/teamList.js
  src/components/teamList/teamTemplates.js
  src/components/todoList/addTodo.js
  src/components/todoList/controlTodo.js
  src/components/todoList/deleteAllTodos.js
  src/components/todoList/editPriority.js
  src/components/todoList/editTodo.js
  src/components/todoList/filterByPriority.js
  src/components/todoList/filterTodo.js
  src/components/todoList/loadTodos.js
  src/components/todoList/todoList.js
  src/components/todoList/todoTemplates.js
  src/index.js
  src/kanban.js
  src/utils/collection.js
  src/utils/constant.js
  src/utils/localStorage.js
Labels: TeamC

#33 [6기 시경덕] TodoList for Team
  .gitignore
  css/style.css
  index.html
  js/App.js
  js/Team.js
  js/apis/Team.js
  js/apis/Todo.js
  js/apis/User.js
  js/apis/common.js
  js/apis/index.js
  js/components/Member/MemberApp.js
  js/components/Member/MemberList.js
  js/components/Member/MemberTitle.js
  js/components/Team/TeamApp.js
  js/components/Team/TeamList.js
  js/components/Todo/TodoApp.js
  js/components/Todo/TodoCount.js
  js/components/Todo/TodoInput.js
  js/components/Todo/TodoList.js
  js/components/index.js
  js/index.js
  js/kanban.js
  js/utils.js
  kanban.html
Labels: TeamD

#34 [6기 조윤호] TodoList For Team
  .eslintrc.json
  .gitignore
  .prettierrc
  css/style.css
  cypress.json
  index.html
  js/App.js
  js/Team.js
  kanban.html
  package.json
  src/api/api.js
  src/kanban/Kanban.js
  src/kanban/components/member/addMember.js
  src/kanban/components/member/loadMembers.js
  src/kanban/components/render/renderMember.js
  src/kanban/components/render/renderTodo.js
  src/kanban/components/todo/addTodo.js
  src/kanban/components/todo/changePriority.js
  src/kanban/components/todo/deleteTodo.js
  src/kanban/components/todo/deleteTodos.js
  src/kanban/components/todo/editTodo.js
  src/kanban/components/todo/filterTodo.js
  src/kanban/components/todo/toggleTodo.js
  src/kanban/handler/handleClickTodoList.js
  src/kanban/handler/handleInputTodoList.js
  src/kanban/handler/onEditTodo.js
  src/kanban/handler/onPriorityTodo.js
  src/team/Team.js
  src/team/components/addTeam.js
  src/team/components/deleteTeam.js
  src/team/components/loadTeam.js
  src/team/handler/handleTeamList.js
  src/team/render/renderTeam.js
  src/utils/constant.js
  src/utils/localStorage.js
  src/utils/validator.js
  yarn.lock
Labels: TeamD, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청
